//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_exam_apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_services
    {
        public int id { get; set; }
        public Nullable<int> blood { get; set; }
        public Nullable<int> service { get; set; }
        public string result { get; set; }
        public string finished { get; set; }
        public string accepted { get; set; }
        public string status { get; set; }
        public string analyzer { get; set; }
        public Nullable<int> user { get; set; }
    
        public virtual blood blood1 { get; set; }
        public virtual services services { get; set; }
        public virtual Users Users { get; set; }
    }
}
