//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_exam_apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LastSeans { get; set; }
        public string Services { get; set; }
        public string Accounts { get; set; }
        public Nullable<int> Post { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual Post Post1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
