//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_exam_apteka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chemist_shopEntities4 : DbContext
    {
        public chemist_shopEntities4()
            : base("name=chemist_shopEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analyzers> Analyzers { get; set; }
        public virtual DbSet<blood> blood { get; set; }
        public virtual DbSet<blood_services> blood_services { get; set; }
        public virtual DbSet<DoneServices> DoneServices { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<InsuranceCompanies> InsuranceCompanies { get; set; }
        public virtual DbSet<Laboratory_services> Laboratory_services { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderServices> OrderServices { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfInsurancePolicy> TypeOfInsurancePolicy { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
