//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_exam_apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int ID_Patients { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string social_sec_number { get; set; }
        public string ein { get; set; }
        public string social_type { get; set; }
        public string phone { get; set; }
        public string passport_s { get; set; }
        public string passport_n { get; set; }
        public string birthdate_timestamp { get; set; }
        public string country { get; set; }
        public string insurance_name { get; set; }
        public string insurance_address { get; set; }
        public string insurance_inn { get; set; }
        public string insurance_p_c { get; set; }
        public string insurance_bik { get; set; }
    }
}
