//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_exam_apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.blood_services = new HashSet<blood_services>();
            this.DoneServices = new HashSet<DoneServices>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string ip { get; set; }
        public string lastenter { get; set; }
        public string services { get; set; }
        public string type { get; set; }
        public Nullable<int> Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blood_services> blood_services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoneServices> DoneServices { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
